const LOAD_MOVIE = "LOAD_MOVIE";
const SET_MOVIE = "SET_MOVIE";
const SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE";
const LOAD_SELECTED_MOVIE = "LOAD_SELECTED_MOVIE";
const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_TOTAL = 'SET_TOTAL';
const LOAD_SEARCH_MOVIE = 'LOAD_SEARCH_MOVIE'

export {
	LOAD_MOVIE,
	SET_MOVIE,
	SET_SELECTED_MOVIE,
	LOAD_SELECTED_MOVIE,
	SET_SEARCH_VALUE,
    SET_CURRENT_PAGE,
    SET_TOTAL,
    LOAD_SEARCH_MOVIE,
    
};
